language: bash
services: docker

env:
  - GLIDE=v0.12.3 VERSION=1.8 VARIANT=  ALIASES="latest,1.8,1"
  - GLIDE=v0.12.3 VERSION=1.8 VARIANT=wheezy
  - GLIDE=v0.12.3 VERSION=1.8 VARIANT=alpine
  - GLIDE=v0.12.3 VERSION=1.7 VARIANT= ALIASES="1.7"
  - GLIDE=v0.12.3 VERSION=1.7 VARIANT=wheezy
  - GLIDE=v0.12.3 VERSION=1.7 VARIANT=alpine
  - GLIDE=v0.12.3 VERSION=1.7 VARIANT=alpine3.5

before_script:
  - env | sort
  - cd "$VERSION"
  - prefix="harborfront/go-glide"
  - image="$prefix:${VERSION:+$VERSION}${GLIDE:+-$GLIDE}${VARIANT:+-$VARIANT}"

script:
  - travis_retry docker build --build-arg="TAG=${GLIDE:+$GLIDE}" -t "$image" "${VARIANT:-.}"

after_script: ./build/aliases.sh
